import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BookOpenIcon, CheckIcon, DocumentTextIcon, EllipsisHorizontalIcon, ExclamationTriangleIcon, MicrophoneIcon, SpeakerWaveIcon, XMarkIcon } from '@heroicons/react/24/solid'
import './styles.css'

const API = 'http://127.0.0.1:8765'
const officeAsset = { word: './0877fc4cdb9ff70b4647ad05d5aba6684812b1f4.png', onenote: './af2a6280cc6e6d04267283dd9a5d00d2fad440fc.png' }
const post = (path, body = {}) => fetch(`${API}${path}`, { method: 'POST', body: JSON.stringify(body) })
function StatusIcon({ notice }) { if (notice.app) return <img src={officeAsset[notice.app]} />; if (notice.kind === 'success') return <CheckIcon />; if (notice.kind === 'recording') return <MicrophoneIcon />; if (notice.kind === 'error' && notice.details?.code === 48) return <SpeakerWaveIcon />; if (notice.kind === 'error') return <ExclamationTriangleIcon />; return <EllipsisHorizontalIcon /> }
function Toast({ notice, leaving }) { return <div className={`toast ${notice.kind} ${leaving ? 'leaving' : ''}`}><span className="toast-icon"><StatusIcon notice={notice} /></span><span className={notice.kind === 'work' ? 'shimmer' : ''}>{notice.text}</span></div> }
function DocIcon({ type }) { return type === 'word' || type === 'onenote' ? <img className="document-app-icon" src={officeAsset[type]} /> : type === 'selection' || type === 'pdf' ? <DocumentTextIcon /> : <BookOpenIcon /> }
function useServerState() { const [state, setState] = useState({ question: { status: 'idle' }, context: [], panels: {} }); useEffect(() => { const refresh = () => fetch(`${API}/state`).then(r => r.json()).then(setState).catch(() => {}); refresh(); const id = setInterval(refresh, 170); return () => clearInterval(id) }, []); return state }
function SurfaceHeader({ title, shortcut, onClose }) { return <><header className="surface-header"><h1>{title}</h1><div className="dismiss"><span>pour quitter : {shortcut}</span><button aria-label="Fermer" onClick={onClose}><XMarkIcon /></button></div></header><div className="surface-rule" /></> }
function ContextPanel() { const state = useServerState(); const [items, setItems] = useState([]); const [selected, setSelected] = useState(() => new Set()); const refresh = () => fetch(`${API}/context-candidates`).then(r => r.json()).then(data => setItems(data.items || [])).catch(() => {}); useEffect(() => { refresh() }, []); useEffect(() => setSelected(new Set((state.context || []).map(item => item.id))), [state.context]); const chosen = useMemo(() => items.filter(item => selected.has(item.id)), [items, selected]); const toggle = item => setSelected(previous => { const next = new Set(previous); next.has(item.id) ? next.delete(item.id) : next.add(item.id); return next }); return <main className="panel-surface"><section className="figma-card context-panel"><SurfaceHeader title="Contexte cours question" shortcut={state.contextShortcut || 'Ctrl + Alt + C'} onClose={() => post('/context-panel-close')} /><div className="context-cards">{items.map(item => <button key={item.id} className="course-card" onClick={() => toggle(item)}><span className="course-icon"><DocIcon type={item.type} /></span><strong title={item.title}>{item.title}</strong><span className={`figma-check ${selected.has(item.id) ? 'checked' : ''}`}>{selected.has(item.id) && <CheckIcon />}</span></button>)}{!items.length && <p className="panel-empty">Aucun document ouvert détecté.</p>}</div><button className="keep-selection" onClick={() => post('/context', { items: chosen })}>Garder cette sélection</button></section></main> }
function AnswerPanel() { const state = useServerState(); const question = state.question || {}; return <main className="panel-surface"><section className="figma-card answer-panel"><SurfaceHeader title={question.question || ' '} shortcut={state.questionShortcut || 'Ctrl + Alt + Q'} onClose={() => post('/question-close')} /><article className="answer-copy">{(question.answer || '').split('\n').filter(Boolean).map((line, index) => <p key={index}>{line}</p>)}</article></section></main> }
function ControlApp() { const state = useServerState(); const question = state.question || {}; const [shortcut, setShortcut] = useState(''); const [questionShortcut, setQuestionShortcut] = useState(''); const [contextShortcut, setContextShortcut] = useState(''); useEffect(() => { setShortcut(state.shortcut || ''); setQuestionShortcut(state.questionShortcut || ''); setContextShortcut(state.contextShortcut || '') }, [state.shortcut, state.questionShortcut, state.contextShortcut]); return <main className="app-shell"><section className="control-card"><header><p>VOICE NOTES</p><h1>Commandes et journal</h1></header><div className="control-actions"><button className={`record-button ${state.recording ? 'is-recording' : ''}`} onClick={() => post(state.recording ? '/stop' : '/start')} disabled={state.busy && !state.recording}><MicrophoneIcon />{state.recording ? 'Terminer l’enregistrement' : state.busy ? 'Finalisation en cours…' : 'Démarrer l’enregistrement'}</button><button className={`question-button ${question.status === 'listening' ? 'is-listening' : ''}`} onClick={() => post('/question-toggle')} disabled={state.recording || state.busy || question.status === 'thinking'}><MicrophoneIcon />{question.status === 'listening' ? 'Terminer la question' : 'Écoute de la question'}</button><button className="context-button" onClick={() => post('/context-panel-open')}>Sélection du contexte</button></div><div className="shortcut-grid"><label>Raccourci transcription<input value={shortcut} onChange={e => setShortcut(e.target.value)} onBlur={e => post('/hotkey', { value: e.target.value })} /></label><label>Raccourci question<input value={questionShortcut} onChange={e => setQuestionShortcut(e.target.value)} onBlur={e => post('/question-hotkey', { value: e.target.value })} /></label><label>Raccourci contexte<input value={contextShortcut} onChange={e => setContextShortcut(e.target.value)} onBlur={e => post('/context-hotkey', { value: e.target.value })} /></label></div><div className="logs">{(state.logs || []).map((line, i) => <p key={i}>{line}</p>)}</div></section></main> }
function App() { const surface = new URLSearchParams(window.location.search).get('surface'); const state = useServerState(); const [notice, setNotice] = useState(null); const [leaving, setLeaving] = useState(false); useEffect(() => { if (state.notice) { setNotice(state.notice); setLeaving(false); return } if (!notice) return; setLeaving(true); const id = setTimeout(() => { setNotice(null); setLeaving(false) }, 240); return () => clearTimeout(id) }, [state.notice]); if (surface === 'toast') return <main className="toast-surface">{notice && <Toast notice={notice} leaving={leaving} />}</main>; if (surface === 'context') return <ContextPanel />; if (surface === 'answer') return <AnswerPanel />; return <ControlApp /> }
createRoot(document.getElementById('root')).render(<App />)
